import { Emojis, Time } from '@utils/constants';
import { resolveEmoji } from '@utils/util';
import { Client } from 'klasa';

export default Client.defaultGuildSchema
	.add('commandUses', 'Integer', { 'default': 0, 'configurable': false })
	.add('prefix', 'string', { filter: (_client, value) => (value as string).length > 10 })
	.add('custom-commands', 'CustomCommand', { array: true, configurable: false })
	.add('permissions.users', 'PermissionNode', { array: true, configurable: false })
	.add('permissions.roles', 'PermissionNode', { array: true, configurable: false })
	.add('channels.announcements', 'TextChannel')
	.add('channels.greeting', 'TextChannel')
	.add('channels.farewell', 'TextChannel')
	.add('channels.member-logs', 'TextChannel')
	.add('channels.message-logs', 'TextChannel')
	.add('channels.moderation-logs', 'TextChannel')
	.add('channels.nsfw-message-logs', 'TextChannel')
	.add('channels.image-logs', 'TextChannel')
	.add('channels.prune-logs', 'TextChannel')
	.add('channels.reaction-logs', 'TextChannel')
	.add('channels.roles', 'TextChannel')
	.add('channels.spam', 'TextChannel')
	.add('command-autodelete', 'any', { array: true })
	.add('disabledChannels', 'TextChannel', { array: true })
	.add('disabledCommandsChannels', 'any', { array: true, configurable: false })
	.add('events.banAdd', 'Boolean', { 'default': false })
	.add('events.banRemove', 'Boolean', { 'default': false })
	.add('events.memberAdd', 'Boolean', { 'default': false })
	.add('events.memberRemove', 'Boolean', { 'default': false })
	.add('events.memberNameUpdate', 'Boolean', { 'default': false })
	.add('events.memberRoleUpdate', 'Boolean', { 'default': false })
	.add('events.messageDelete', 'Boolean', { 'default': false })
	.add('events.messageEdit', 'Boolean', { 'default': false })
	.add('events.twemoji-reactions', 'Boolean', { 'default': false })
	.add('messages.farewell', 'String', { maximum: 2000 })
	.add('messages.greeting', 'String', { maximum: 2000 })
	.add('messages.join-dm', 'String', { maximum: 1500 })
	.add('messages.ignoreChannels', 'TextChannel', { array: true })
	.add('messages.announcement-embed', 'Boolean', { 'default': false })
	.add('messages.moderation-dm', 'Boolean', { 'default': false })
	.add('messages.moderation-reason-display', 'Boolean', { 'default': true })
	.add('messages.moderation-message-display', 'Boolean', { 'default': true })
	.add('messages.moderation-auto-delete', 'Boolean', { 'default': false })
	.add('messages.moderator-name-display', 'Boolean', { 'default': true })
	.add('stickyRoles', 'any', { array: true })
	.add('roles.admin', 'Role')
	.add('roles.auto', 'any', { array: true })
	.add('roles.initial', 'Role')
	.add('roles.messageReaction', 'Snowflake', { configurable: false })
	.add('roles.moderator', 'Role')
	.add('roles.muted', 'Role')
	.add('roles.restricted-reaction', 'Role')
	.add('roles.restricted-embed', 'Role')
	.add('roles.restricted-emoji', 'Role')
	.add('roles.restricted-attachment', 'Role')
	.add('roles.restricted-voice', 'Role')
	.add('roles.public', 'Role', { array: true })
	.add('roles.reactions', 'any', { array: true })
	.add('roles.removeInitial', 'Boolean')
	.add('roles.dj', 'Role')
	.add('roles.subscriber', 'Role')
	.add('roles.uniqueRoleSets', 'any', { array: true })
	.add('selfmod.attachment', 'Boolean', { 'default': false })
	.add('selfmod.attachmentMaximum', 'Integer', { 'default': 20, 'minimum': 0, 'maximum': 60 })
	.add('selfmod.attachmentDuration', 'Integer', { 'default': 20000, 'minimum': 5000, 'maximum': 120000, 'configurable': false })
	.add('selfmod.attachmentAction', 'Integer', { 'default': 0, 'configurable': false })
	.add('selfmod.attachmentPunishmentDuration', 'Integer', { configurable: false })
	.add('selfmod.capitals.enabled', 'Boolean', { 'default': false })
	.add('selfmod.capitals.ignoredRoles', 'Role', { array: true })
	.add('selfmod.capitals.ignoredChannels', 'TextChannel', { array: true })
	.add('selfmod.capitals.minimum', 'Integer', { 'default': 15, 'minimum': 5, 'maximum': 2000 })
	.add('selfmod.capitals.maximum', 'Integer', { 'default': 50, 'minimum': 10, 'maximum': 100 })
	.add('selfmod.capitals.softAction', 'Integer', { 'default': 0, 'configurable': false })
	.add('selfmod.capitals.hardAction', 'Integer', { 'default': 0, 'configurable': false })
	.add('selfmod.capitals.hardActionDuration', 'Integer', { minimum: 1000, configurable: false })
	.add('selfmod.capitals.thresholdMaximum', 'Integer', { 'default': 10, 'minimum': 0, 'maximum': 60, 'configurable': false })
	.add('selfmod.capitals.thresholdDuration', 'Integer', { 'default': 60000, 'minimum': 0, 'maximum': 120000, 'configurable': false })
	.add('selfmod.links.whitelist', 'URL', { array: true })
	.add('selfmod.links.enabled', 'Boolean', { 'default': false })
	.add('selfmod.links.ignoredRoles', 'Role', { array: true })
	.add('selfmod.links.ignoredChannels', 'TextChannel', { array: true })
	.add('selfmod.links.softAction', 'Integer', { 'default': 0, 'configurable': false })
	.add('selfmod.links.hardAction', 'Integer', { 'default': 0, 'configurable': false })
	.add('selfmod.links.hardActionDuration', 'Integer', { minimum: 1000, configurable: false })
	.add('selfmod.links.thresholdMaximum', 'Integer', { 'default': 10, 'minimum': 0, 'maximum': 60, 'configurable': false })
	.add('selfmod.links.thresholdDuration', 'Integer', { 'default': 60000, 'minimum': 0, 'maximum': 120000, 'configurable': false })
	.add('selfmod.messages.enabled', 'Boolean', { 'default': false })
	.add('selfmod.messages.ignoredRoles', 'Role', { array: true })
	.add('selfmod.messages.ignoredChannels', 'TextChannel', { array: true })
	.add('selfmod.messages.maximum', 'Integer', { 'default': 5, 'minimum': 2, 'maximum': 100 })
	.add('selfmod.messages.queue-size', 'Integer', { 'default': 50, 'minimum': 10, 'maximum': 100 })
	.add('selfmod.messages.softAction', 'Integer', { 'default': 0, 'configurable': false })
	.add('selfmod.messages.hardAction', 'Integer', { 'default': 0, 'configurable': false })
	.add('selfmod.messages.hardActionDuration', 'Integer', { minimum: 1000, configurable: false })
	.add('selfmod.messages.thresholdMaximum', 'Integer', { 'default': 10, 'minimum': 0, 'maximum': 60, 'configurable': false })
	.add('selfmod.messages.thresholdDuration', 'Integer', { 'default': 60000, 'minimum': 0, 'maximum': 120000, 'configurable': false })
	.add('selfmod.newlines.enabled', 'Boolean', { 'default': false })
	.add('selfmod.newlines.ignoredRoles', 'Role', { array: true })
	.add('selfmod.newlines.ignoredChannels', 'TextChannel', { array: true })
	.add('selfmod.newlines.maximum', 'Integer', { 'default': 20, 'minimum': 10, 'maximum': 2000 })
	.add('selfmod.newlines.softAction', 'Integer', { 'default': 0, 'configurable': false })
	.add('selfmod.newlines.hardAction', 'Integer', { 'default': 0, 'configurable': false })
	.add('selfmod.newlines.hardActionDuration', 'Integer', { minimum: 1000, configurable: false })
	.add('selfmod.newlines.thresholdMaximum', 'Integer', { 'default': 10, 'minimum': 0, 'maximum': 60, 'configurable': false })
	.add('selfmod.newlines.thresholdDuration', 'Integer', { 'default': 60000, 'minimum': 0, 'maximum': 120000, 'configurable': false })
	.add('selfmod.invites.enabled', 'Boolean', { 'default': false })
	.add('selfmod.invites.ignoredCodes', 'Invite', { array: true })
	.add('selfmod.invites.ignoredGuilds', 'Snowflake', { array: true })
	.add('selfmod.invites.ignoredRoles', 'Role', { array: true })
	.add('selfmod.invites.ignoredChannels', 'TextChannel', { array: true })
	.add('selfmod.invites.softAction', 'Integer', { 'default': 0, 'configurable': false })
	.add('selfmod.invites.hardAction', 'Integer', { 'default': 0, 'configurable': false })
	.add('selfmod.invites.hardActionDuration', 'Integer', { minimum: 1000, configurable: false })
	.add('selfmod.invites.thresholdMaximum', 'Integer', { 'default': 10, 'minimum': 0, 'maximum': 60, 'configurable': false })
	.add('selfmod.invites.thresholdDuration', 'Integer', { 'default': 60000, 'minimum': 0, 'maximum': 120000, 'configurable': false })
	.add('selfmod.filter.raw', 'String', { array: true, maximum: 32, configurable: false })
	.add('selfmod.filter.enabled', 'Boolean', { 'default': false })
	.add('selfmod.filter.ignoredRoles', 'Role', { array: true })
	.add('selfmod.filter.ignoredChannels', 'TextChannel', { array: true })
	.add('selfmod.filter.softAction', 'Integer', { 'default': 0, 'configurable': false })
	.add('selfmod.filter.hardAction', 'Integer', { 'default': 0, 'configurable': false })
	.add('selfmod.filter.hardActionDuration', 'Integer', { minimum: 1000, configurable: false })
	.add('selfmod.filter.thresholdMaximum', 'Integer', { 'default': 10, 'minimum': 0, 'maximum': 60, 'configurable': false })
	.add('selfmod.filter.thresholdDuration', 'Integer', { 'default': 60000, 'minimum': 0, 'maximum': 120000, 'configurable': false })
	.add('selfmod.reactions.maximum', 'Integer', { 'default': 10, 'minimum': 1, 'maximum': 100 })
	.add('selfmod.reactions.whitelist', 'Emoji', { array: true })
	.add('selfmod.reactions.blacklist', 'Emoji', { array: true })
	.add('selfmod.reactions.enabled', 'Boolean', { 'default': false })
	.add('selfmod.reactions.ignoredRoles', 'Role', { array: true })
	.add('selfmod.reactions.ignoredChannels', 'TextChannel', { array: true })
	.add('selfmod.reactions.softAction', 'Integer', { 'default': 0, 'configurable': false })
	.add('selfmod.reactions.hardAction', 'Integer', { 'default': 0, 'configurable': false })
	.add('selfmod.reactions.hardActionDuration', 'Integer', { minimum: 1000, configurable: false })
	.add('selfmod.reactions.thresholdMaximum', 'Integer', { 'default': 10, 'minimum': 0, 'maximum': 60, 'configurable': false })
	.add('selfmod.reactions.thresholdDuration', 'Integer', { 'default': 60000, 'minimum': 0, 'maximum': 120000, 'configurable': false })
	.add('selfmod.raid', 'Boolean')
	.add('selfmod.raidthreshold', 'Integer', { 'default': 10, 'minimum': 2, 'maximum': 50 })
	.add('selfmod.ignoreChannels', 'TextChannel', { array: true })
	.add('no-mention-spam.enabled', 'Boolean', { 'default': false })
	.add('no-mention-spam.alerts', 'Boolean', { 'default': false })
	.add('no-mention-spam.mentionsAllowed', 'Integer', { 'default': 20, 'minimum': 0 })
	.add('no-mention-spam.timePeriod', 'Integer', { 'default': 8, 'minimum': 0 })
	.add('social.enabled', 'Boolean', { 'default': true })
	.add('social.achieve', 'Boolean', { 'default': false })
	.add('social.achieveMessage', 'String')
	.add('social.multiplier', 'Number', { 'default': 1, 'minimum': 0, 'maximum': 5 })
	.add('social.ignoreChannels', 'TextChannel', { array: true })
	.add('starboard.channel', 'TextChannel')
	.add('starboard.emoji', 'String', { 'default': '%E2%AD%90', 'configurable': false })
	.add('starboard.ignoreChannels', 'TextChannel', { array: true })
	.add('starboard.minimum', 'Integer', { 'default': 1, 'minimum': 1, 'inclusive': true })
	.add('trigger.alias', 'any', { array: true, configurable: false })
	.add('trigger.includes', 'any', { array: true, configurable: false })
	.add('music.default-volume', 'Number', { 'minimum': 0, 'maximum': 200, 'default': 100 })
	.add('music.maximum-duration', 'Number', { 'minimum': 0, 'maximum': Time.Hour * 12, 'default': Time.Hour * 2 })
	.add('music.maximum-entries-per-user', 'Number', { 'minimum': 1, 'maximum': 250, 'default': 100 })
	.add('music.allow-streams', 'Boolean', { 'default': true })
	.add('notifications.streams.twitch.streamers', 'TwitchSubscription', { array: true, configurable: false })
	.add('suggestions.channel', 'TextChannel')
	.add('suggestions.id', 'integer', { 'minimum': 1, 'default': 1, 'configurable': false })
	.add('suggestions.emojis.upvote', 'Emoji', { 'default': resolveEmoji(Emojis.ArrowT) })
	.add('suggestions.emojis.downvote', 'Emoji', { 'default': resolveEmoji(Emojis.ArrowB) })
	.add('suggestions.on-action.dm', 'Boolean', { 'default': false })
	.add('suggestions.on-action.repost', 'Boolean', { 'default': false })
	.add('suggestions.on-action.hide-author', 'Boolean', { 'default': false });
